-- =====================================================================
-- Feature 1 — Planejamento Mensal
-- Rodar no SQL Editor do Supabase (uma única vez).
-- =====================================================================

-- Planos mensais (1 plano por mês; mês deletado → plano deletado junto)
create table monthly_plans (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users default auth.uid(),
  month_id   bigint not null references months(id) on delete cascade,
  income     numeric not null default 0,
  status     text not null default 'ativo',   -- ativo | fechado
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (month_id)
);

-- Itens do plano (alocação por categoria)
create table monthly_plan_items (
  id               bigint generated by default as identity primary key,
  plan_id          bigint not null references monthly_plans(id) on delete cascade,
  user_id          uuid not null references auth.users default auth.uid(),
  category         text not null,
  suggested_amount numeric,                    -- valor calculado pelo algoritmo
  planned_amount   numeric not null default 0, -- valor confirmado pelo usuário
  is_eventual      boolean default false,      -- gasto esporádico (badge na UI)
  is_mandatory     boolean default false,      -- reservado p/ Feature 2 (dívidas)
  unique (plan_id, category)
);

-- RLS (mesmo padrão das tabelas existentes)
alter table monthly_plans enable row level security;
alter table monthly_plan_items enable row level security;

create policy "monthly_plans_all" on monthly_plans
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "monthly_plan_items_all" on monthly_plan_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
