-- =====================================================================
-- Feature 2 — Módulo de Dívidas
-- Rodar no SQL Editor do Supabase (uma única vez), após a migração 001.
-- =====================================================================

-- Dívidas (a entidade)
create table debts (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users default auth.uid(),
  description  text not null,
  creditor     text,
  total_amount numeric not null,
  category     text default 'Dívidas',
  notes        text,
  created_at   timestamptz default now()
);

-- Parcelas (dívida à vista = 1 parcela)
create table debt_installments (
  id                 bigint generated by default as identity primary key,
  debt_id            bigint not null references debts(id) on delete cascade,
  user_id            uuid not null references auth.users default auth.uid(),
  installment_number int not null default 1,
  amount             numeric not null,
  due_year           int not null,
  due_month          int not null,        -- 1 a 12
  paid_at            timestamptz,         -- null = pendente
  expense_id         bigint,              -- transactions.id do gasto gerado
  unique (debt_id, installment_number)
);

-- Status é derivado na leitura (não há coluna):
--   paid_at preenchido                          → paga
--   (due_year, due_month) < mês atual e ñ paga  → atrasada
--   senão                                       → pendente

alter table debts enable row level security;
alter table debt_installments enable row level security;

create policy "debts_all" on debts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "debt_installments_all" on debt_installments
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
