-- =====================================================================
-- Feature 3 — Vale Refeição / Vale Alimentação (benefícios)
-- Rodar no SQL Editor do Supabase (uma única vez), após as migrações 001 e 002.
-- =====================================================================

-- Benefícios (VR / VA) — saldo carimbado que renova num dia fixo do mês
create table benefit_cards (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references auth.users default auth.uid(),
  name            text not null,
  benefit_type    text not null check (benefit_type in ('VR','VA')),
  balance         numeric not null default 0,
  renewal_day     int not null check (renewal_day between 1 and 31),  -- 29-31: renova no último dia do mês
  recharge_amount numeric not null default 0,
  recharge_mode   text not null default 'acumula' check (recharge_mode in ('acumula','zera')),
  last_renewal    date,
  color           text default '#2EAF7D',
  archived_at     timestamptz,   -- exclusão = arquiva (mantém gastos vinculados)
  created_at      timestamptz default now()
);

-- Histórico de renovações (auditoria)
create table benefit_renewals (
  id              bigint generated by default as identity primary key,
  benefit_id      bigint not null references benefit_cards(id) on delete cascade,
  user_id         uuid not null references auth.users default auth.uid(),
  renewed_at      date not null,
  amount          numeric not null,
  balance_before  numeric not null,
  balance_after   numeric not null,
  created_at      timestamptz default now()
);

-- Liga um gasto a um benefício (dinheiro carimbado, fora dos envelopes do plano)
alter table transactions add column if not exists benefit_id bigint references benefit_cards(id) on delete set null;

alter table benefit_cards    enable row level security;
alter table benefit_renewals enable row level security;

create policy "benefit_cards_all" on benefit_cards
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "benefit_renewals_all" on benefit_renewals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
