-- =====================================================================
-- Feature 5 (web) — Cartões de Débito (exclusivo web/mobile)
-- Tabela própria e separada de credit_cards de propósito: cartão de
-- débito não tem fatura/vencimento/limite, e uma tabela separada evita
-- qualquer risco de quebrar o app desktop (que só entende credit_cards
-- com due_day/closing_day sempre preenchidos). O app desktop nunca lê
-- nem grava nesta tabela nem na coluna debit_card_id — para ele, essas
-- transações aparecem como uma saída comum (debita o saldo na hora,
-- igual a "Nenhuma origem" já se comporta hoje).
-- Rodar no SQL Editor do Supabase (após 001-008).
-- =====================================================================

create table debit_cards (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users default auth.uid(),
  name       text not null,
  color      text default '#6C8EFF',
  created_at timestamptz default now()
);

alter table debit_cards enable row level security;

create policy "debit_cards_all" on debit_cards
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Liga um gasto a um cartão de débito (apenas rótulo/tag — não afeta
-- nenhum cálculo de saldo/envelope, exatamente como uma transação sem
-- origem já funciona)
alter table transactions add column if not exists debit_card_id bigint references debit_cards(id) on delete set null;

-- Pix não é uma entidade cadastrável (não tem nome/cor por card) — é só
-- um rótulo fixo de forma de pagamento, mesma ideia do débito: não afeta
-- nenhum cálculo, é puramente informativo.
alter table transactions add column if not exists payment_method text;

-- Gasto do mês por cartão de débito (para a lista da tela de Cartões)
create or replace function get_debit_cards_overview(p_month_id bigint)
returns table (id bigint, name text, color text, spent numeric)
language sql
stable
as $$
  select
    d.id, d.name, d.color,
    coalesce(sum(t.amount) filter (
      where t.type = 'saida_variavel' and coalesce(t.is_expectation, false) = false
    ), 0) as spent
  from debit_cards d
  left join transactions t
    on t.debit_card_id = d.id and t.month_id = p_month_id
  group by d.id, d.name, d.color
  order by d.created_at;
$$;

-- add_transaction / update_transaction precisam do novo parâmetro
-- p_debit_card_id. Como isso muda a assinatura (nº de parâmetros),
-- é necessário DROP + CREATE (CREATE OR REPLACE não troca assinatura).
drop function if exists add_transaction(bigint, text, text, numeric, text, bigint, bigint, boolean);
drop function if exists update_transaction(bigint, text, numeric, text, bigint, bigint, boolean);

create or replace function add_transaction(
  p_month_id       bigint,
  p_type           text,
  p_description    text,
  p_amount         numeric,
  p_category       text default 'Outros',
  p_card_id        bigint default null,
  p_benefit_id     bigint default null,
  p_is_expectation boolean default false,
  p_debit_card_id  bigint default null,
  p_payment_method text default null
) returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  insert into transactions (
    month_id, user_id, type, description, amount, category,
    card_id, benefit_id, is_expectation, debit_card_id, payment_method
  ) values (
    p_month_id, auth.uid(), p_type, p_description, p_amount,
    coalesce(p_category, 'Outros'), p_card_id, p_benefit_id,
    coalesce(p_is_expectation, false), p_debit_card_id, p_payment_method
  )
  returning id into v_id;

  -- Gasto com VR/VA debita o saldo na hora (previsão não debita)
  if p_benefit_id is not null and not coalesce(p_is_expectation, false) then
    update benefit_cards set balance = balance - p_amount where id = p_benefit_id;
  end if;

  return v_id;
end;
$$;

create or replace function update_transaction(
  p_id             bigint,
  p_description    text,
  p_amount         numeric,
  p_category       text,
  p_card_id        bigint default null,
  p_benefit_id     bigint default null,
  p_is_expectation boolean default false,
  p_debit_card_id  bigint default null,
  p_payment_method text default null
) returns void
language plpgsql
as $$
declare
  v_old transactions;
begin
  select * into v_old from transactions where id = p_id;
  if not found then return; end if;

  if v_old.benefit_id is not null and not coalesce(v_old.is_expectation, false) then
    update benefit_cards set balance = balance + v_old.amount where id = v_old.benefit_id;
  end if;

  update transactions set
    description    = p_description,
    amount         = p_amount,
    category       = coalesce(p_category, 'Outros'),
    card_id        = p_card_id,
    benefit_id     = p_benefit_id,
    is_expectation = coalesce(p_is_expectation, false),
    debit_card_id  = p_debit_card_id,
    payment_method = p_payment_method
  where id = p_id;

  if p_benefit_id is not null and not coalesce(p_is_expectation, false) then
    update benefit_cards set balance = balance - p_amount where id = p_benefit_id;
  end if;
end;
$$;

grant execute on function get_debit_cards_overview(bigint)                                                          to authenticated;
grant execute on function add_transaction(bigint, text, text, numeric, text, bigint, bigint, boolean, bigint, text) to authenticated;
grant execute on function update_transaction(bigint, text, numeric, text, bigint, bigint, boolean, bigint, text)    to authenticated;
