-- =====================================================================
-- Corrige o "gasto no ciclo"/"disponível"/"Pagar Fatura" do cartão de
-- crédito sumindo assim que o ciclo fecha, e adiciona histórico de
-- faturas.
--
-- Causa raiz do bug: get_cards_overview e get_future_commitments somavam
-- transactions.created_at::date >= _cycle_start(closing_day) -- e
-- _cycle_start sempre devolve o início do ciclo que contém HOJE. Certo
-- enquanto o ciclo está aberto (soma o gasto acumulando em tempo real),
-- errado assim que fecha: nesse momento _cycle_start pula pro ciclo NOVO
-- (que acabou de começar, quase sempre vazio), e a fatura fechada
-- aguardando pagamento fica invisível até ser paga -- pay_card_bill tinha
-- o mesmo problema (procurava pra pagar no ciclo novo errado, não achava
-- nada). Também trocamos created_at (quando a linha foi criada no banco,
-- sem relação com a data real da compra) por payment_date.
--
-- Também muda o modelo de pagamento: em vez de apagar as transações e
-- criar um lançamento único consolidado (perdendo o detalhe), "Pagar
-- Fatura" agora só marca as transações como faturadas (invoice_id) --
-- elas continuam existindo e aparecendo em Lançamentos normalmente, e
-- passam a alimentar um histórico de faturas navegável por cartão.
-- "Gasto no ciclo" só zera quando o usuário paga OU quando a data de
-- vencimento passa (settle_due_card_invoices trata esse segundo caso,
-- chamada uma vez por sessão do app -- mesmo padrão já usado pelas
-- renovações de VR/VA).
--
-- Rodar no SQL Editor do Supabase (após 001-034).
-- =====================================================================

create table card_invoices (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users default auth.uid(),
  card_id      bigint not null references credit_cards(id) on delete cascade,
  cycle_start  date not null,
  due_date     date not null,
  total        numeric not null default 0,
  paid_at      timestamptz not null default now(),
  auto_settled boolean not null default false,  -- true = quitada sozinha no vencimento, sem clique em "Pagar"
  created_at   timestamptz not null default now()
);

alter table transactions add column if not exists invoice_id bigint references card_invoices(id) on delete set null;

alter table card_invoices enable row level security;

create policy "card_invoices_all" on card_invoices
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Data de vencimento da fatura do ciclo mais recentemente fechado (a que
-- está aguardando pagamento agora), como data absoluta -- reaproveita
-- _cycle_start (já testado) pra achar a data de fechamento, e resolve o
-- mês do vencimento considerando o wrap-around (ex.: fecha dia 25, vence
-- dia 5 -> vencimento é no mês seguinte ao fechamento).
create or replace function _cycle_due_date(p_closing_day int, p_due_day int)
returns date
language plpgsql
stable
as $$
declare
  v_closing_date date := _cycle_start(p_closing_day);
  v_ref_month date;
  v_max_day int;
begin
  if p_due_day >= p_closing_day then
    v_ref_month := date_trunc('month', v_closing_date)::date;
  else
    v_ref_month := (date_trunc('month', v_closing_date) + interval '1 month')::date;
  end if;
  v_max_day := extract(day from (v_ref_month + interval '1 month - 1 day'))::int;
  return make_date(extract(year from v_ref_month)::int, extract(month from v_ref_month)::int,
                    least(p_due_day, v_max_day));
end;
$$;

create or replace function get_cards_overview(p_month_id bigint)
returns table (
  id bigint,
  name text,
  card_limit numeric,
  due_day int,
  closing_day int,
  color text,
  spent numeric,
  paid numeric,
  unpaid numeric,
  available numeric,
  days_until_closing int,
  days_until_due int,
  cycle_open boolean
)
language plpgsql
stable
as $$
begin
  return query
  select
    c.id,
    c.name,
    c."limit" as card_limit,
    c.due_day,
    c.closing_day,
    c.color,
    case when win.is_open then coalesce(open_spend.total, 0)
         else coalesce(closed_spend.total, 0) end as spent,
    coalesce(pay.total, 0) as paid,
    coalesce(closed_spend.total, 0) as unpaid,
    case when c."limit" > 0
         then greatest(0, c."limit" - (coalesce(open_spend.total, 0) + coalesce(closed_spend.total, 0)))
         else null end as available,
    _days_until(c.closing_day) as days_until_closing,
    _days_until(c.due_day) as days_until_due,
    win.is_open as cycle_open
  from credit_cards c
  cross join lateral (
    select
      (extract(day from current_date)::int < c.closing_day) as is_open,
      _cycle_start(c.closing_day) as cycle_start
  ) win
  left join lateral (
    -- ciclo aberto, ainda acumulando (compras reais desde o último fechamento)
    select sum(t.amount) as total
    from transactions t
    where t.card_id = c.id
      and t.type = 'saida_variavel'
      and coalesce(t.is_expectation, false) = false
      and t.invoice_id is null
      and t.payment_date >= win.cycle_start
  ) open_spend on true
  left join lateral (
    -- fatura fechada, ainda não paga nem vencida
    select sum(t.amount) as total
    from transactions t
    where t.card_id = c.id
      and t.type = 'saida_variavel'
      and coalesce(t.is_expectation, false) = false
      and t.invoice_id is null
      and t.payment_date < win.cycle_start
  ) closed_spend on true
  left join lateral (
    -- credit_card_payments não é mais escrita por nenhum fluxo real de
    -- pagamento (pagamento agora é via invoice_id) -- mantido só por
    -- compatibilidade de schema, deve ficar sempre 0.
    select sum(p.amount) as total
    from credit_card_payments p
    where p.card_id = c.id
  ) pay on true
  order by c.created_at;
end;
$$;

create or replace function pay_card_bill(p_card_id bigint, p_month_id bigint)
returns numeric
language plpgsql
as $$
declare
  v_card credit_cards;
  v_cycle_start date;
  v_due date;
  v_total numeric := 0;
  v_min_date date;
  v_invoice_id bigint;
begin
  select * into v_card from credit_cards where id = p_card_id;
  if not found then return 0; end if;

  v_cycle_start := _cycle_start(v_card.closing_day);
  v_due := _cycle_due_date(v_card.closing_day, v_card.due_day);

  select coalesce(sum(amount), 0), min(payment_date) into v_total, v_min_date
  from transactions
  where card_id = p_card_id
    and type = 'saida_variavel'
    and coalesce(is_expectation, false) = false
    and invoice_id is null
    and payment_date < v_cycle_start;

  if v_total <= 0 then
    return 0;
  end if;

  insert into card_invoices (user_id, card_id, cycle_start, due_date, total, paid_at, auto_settled)
  values (auth.uid(), p_card_id, coalesce(v_min_date, v_due), v_due, v_total, now(), false)
  returning id into v_invoice_id;

  update transactions
  set invoice_id = v_invoice_id
  where card_id = p_card_id
    and type = 'saida_variavel'
    and coalesce(is_expectation, false) = false
    and invoice_id is null
    and payment_date < v_cycle_start;

  return v_total;
end;
$$;

-- Quita automaticamente (auto_settled = true) qualquer fatura fechada
-- cujo vencimento já passou e que ainda não foi paga manualmente --
-- chamada uma vez por sessão do app (mesmo padrão de
-- applyAllDueRenewals/apply_due_renewals pras renovações de VR/VA).
-- Retorna quantos cartões foram quitados (0 = nada a fazer).
create or replace function settle_due_card_invoices()
returns int
language plpgsql
as $$
declare
  v_count int := 0;
  v_card record;
  v_total numeric;
  v_due date;
  v_cycle_start date;
  v_min_date date;
  v_invoice_id bigint;
begin
  for v_card in select * from credit_cards where user_id = auth.uid() loop
    v_due := _cycle_due_date(v_card.closing_day, v_card.due_day);
    if v_due > current_date then
      continue; -- ainda não venceu, não mexe
    end if;

    v_cycle_start := _cycle_start(v_card.closing_day);

    select coalesce(sum(amount), 0), min(payment_date) into v_total, v_min_date
    from transactions
    where card_id = v_card.id
      and type = 'saida_variavel'
      and coalesce(is_expectation, false) = false
      and invoice_id is null
      and payment_date < v_cycle_start;

    if v_total <= 0 then
      continue;
    end if;

    insert into card_invoices (user_id, card_id, cycle_start, due_date, total, paid_at, auto_settled)
    values (auth.uid(), v_card.id, coalesce(v_min_date, v_due), v_due, v_total, v_due::timestamptz, true)
    returning id into v_invoice_id;

    update transactions
    set invoice_id = v_invoice_id
    where card_id = v_card.id
      and type = 'saida_variavel'
      and coalesce(is_expectation, false) = false
      and invoice_id is null
      and payment_date < v_cycle_start;

    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

create or replace function get_card_invoices(p_card_id bigint)
returns table (
  id bigint,
  cycle_start date,
  due_date date,
  total numeric,
  paid_at timestamptz,
  auto_settled boolean
)
language sql
stable
as $$
  select id, cycle_start, due_date, total, paid_at, auto_settled
  from card_invoices
  where card_id = p_card_id
  order by cycle_start desc;
$$;

-- get_future_commitments: mesmo ajuste de janela (payment_date +
-- invoice_id em vez de created_at) no open_bill_agg -- mesmo bug do
-- get_cards_overview afetava "Resumo dos Compromissos".
create or replace function get_future_commitments(p_months int default 6)
returns table (
  year int,
  month int,
  card_total numeric,
  debt_total numeric,
  bills_total numeric,
  grand_total numeric
)
language plpgsql
stable
as $$
declare
  v_today date := date_trunc('month', current_date);
begin
  return query
  with months_series as (
    select extract(year from d)::int as yr, extract(month from d)::int as mo
    from generate_series(v_today, v_today + ((greatest(p_months, 1) - 1) || ' months')::interval, interval '1 month') d
  ),
  -- Fatura fechada de cada cartão, ainda não paga nem vencida, rotulada
  -- pelo mês em que aquele ciclo começou (menor payment_date do lote).
  open_bill_raw as (
    select
      c.id,
      sum(t.amount) as total,
      min(t.payment_date) as min_date
    from credit_cards c
    join transactions t on t.card_id = c.id
      and t.type = 'saida_variavel'
      and coalesce(t.is_expectation, false) = false
      and t.invoice_id is null
      and t.payment_date < _cycle_start(c.closing_day)
    group by c.id
  ),
  open_bill_agg as (
    select
      extract(year from greatest(coalesce(min_date, v_today), v_today))::int as yr,
      extract(month from greatest(coalesce(min_date, v_today), v_today))::int as mo,
      sum(total) as total
    from open_bill_raw
    where total > 0
    group by 1, 2
  ),
  -- Parcelas futuras previstas (mês do próprio parcelamento, escolhido
  -- pelo usuário na hora de criar a compra) — não pega a parcela do mês
  -- corrente (is_expectation=false), essa já está no open_bill_agg.
  installment_agg as (
    select extract(year from t.payment_date)::int as yr,
           extract(month from t.payment_date)::int as mo,
           sum(t.amount) as total
    from transactions t
    where t.card_purchase_id is not null and t.is_expectation and t.payment_date is not null
    group by 1, 2
  ),
  card_agg as (
    select coalesce(o.yr, i.yr) as yr, coalesce(o.mo, i.mo) as mo,
           coalesce(o.total, 0) + coalesce(i.total, 0) as total
    from open_bill_agg o
    full outer join installment_agg i on i.yr = o.yr and i.mo = o.mo
  ),
  debt_agg as (
    select due_year as yr, due_month as mo, sum(amount) as total
    from debt_installments
    where paid_at is null
    group by 1, 2
  ),
  bills_agg as (
    select due_year as yr, due_month as mo, sum(amount) as total
    from fixed_bill_instances
    where paid_at is null
    group by 1, 2
  )
  select
    ms.yr, ms.mo,
    coalesce(c.total, 0) as card_total,
    coalesce(d.total, 0) as debt_total,
    coalesce(b.total, 0) as bills_total,
    coalesce(c.total, 0) + coalesce(d.total, 0) + coalesce(b.total, 0) as grand_total
  from months_series ms
  left join card_agg  c on c.yr = ms.yr and c.mo = ms.mo
  left join debt_agg  d on d.yr = ms.yr and d.mo = ms.mo
  left join bills_agg b on b.yr = ms.yr and b.mo = ms.mo
  order by ms.yr, ms.mo;
end;
$$;

grant execute on function _cycle_due_date(int, int)         to authenticated;
grant execute on function get_cards_overview(bigint)        to authenticated;
grant execute on function pay_card_bill(bigint, bigint)     to authenticated;
grant execute on function settle_due_card_invoices()        to authenticated;
grant execute on function get_card_invoices(bigint)         to authenticated;
grant execute on function get_future_commitments(int)       to authenticated;
