-- =====================================================================
-- Feature — Perfil de Investidor
-- Histórico de resultados do questionário de perfil de investidor.
-- Tabela só-de-inserção (nunca update/delete) -- "perfil atual" é
-- sempre a linha mais recente de cada usuário, sem tabela separada.
-- Rodar no SQL Editor do Supabase (após 001-044).
-- =====================================================================

create table investor_profile_results (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users default auth.uid(),
  score      numeric not null,
  profile    text not null,       -- 'Conservador' | 'Moderado' | 'Arrojado'
  answers    jsonb not null,      -- {question_id: option_value, ...} -- nunca
                                   -- agregado/consultado no servidor, só
                                   -- reexibido pro próprio usuário (mesmo
                                   -- precedente de user_settings.dashboard_cards)
  created_at timestamptz not null default now()
);

alter table investor_profile_results enable row level security;

create policy "own investor_profile_results" on investor_profile_results
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
