-- =====================================================================
-- Feature — Metas de alocação por perfil (editável pelo usuário)
-- Cada usuário tem suas próprias metas (% alvo + tolerância) por
-- perfil e classe de ativo. Semeada sob demanda: na primeira leitura
-- sem linhas pra um perfil, a aplicação insere os valores-padrão de
-- utils/target_allocation_defaults.py / targetAllocationDefaults.ts
-- (ver get_target_allocations) -- depois disso é só CRUD direto.
-- Rodar no SQL Editor do Supabase (após 046).
-- =====================================================================

create table investor_target_allocations (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null references auth.users default auth.uid(),
  profile        text not null,       -- 'Conservador' | 'Moderado' | 'Arrojado'
  asset_class    text not null,
  target_pct     numeric not null,    -- fração 0-1
  tolerance_pct  numeric not null,    -- fração 0-1
  updated_at     timestamptz not null default now(),
  unique (user_id, profile, asset_class)
);

alter table investor_target_allocations enable row level security;

create policy "own investor_target_allocations" on investor_target_allocations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
