-- =====================================================================
-- Feature — Carteiras fictícias (simulação)
-- Nunca escreve em transactions/investment_movements -- são tabelas
-- isoladas, sem nenhum efeito em saldo/lançamentos reais.
-- Rodar no SQL Editor do Supabase (após 047).
-- =====================================================================

create table mock_portfolios (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references auth.users default auth.uid(),
  name       text not null,
  source     text not null default 'scratch'
             check (source in ('scratch', 'copy_real', 'copy_target', 'import')),
  value_mode text not null default 'absolute'
             check (value_mode in ('absolute', 'percentage')),
  created_at timestamptz not null default now()
);

create table mock_portfolio_items (
  id                bigint generated by default as identity primary key,
  mock_portfolio_id bigint not null references mock_portfolios(id) on delete cascade,
  user_id           uuid not null references auth.users default auth.uid(),
  asset_class       text not null,
  label             text,
  value             numeric not null default 0 check (value >= 0),
  created_at        timestamptz not null default now()
);

alter table mock_portfolios      enable row level security;
alter table mock_portfolio_items enable row level security;

create policy "own mock_portfolios" on mock_portfolios
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "own mock_portfolio_items" on mock_portfolio_items
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Cria a carteira fictícia + todos os itens numa única operação --
-- mesmo padrão de create_investment (013) e import_transactions_bulk
-- (014/032): parâmetro jsonb só como conveniência de transporte,
-- sempre insere em tabelas normalizadas de verdade.
create or replace function create_mock_portfolio_bulk(
  p_name       text,
  p_source     text,
  p_value_mode text,
  p_items      jsonb
) returns bigint
language plpgsql
as $$
declare
  v_id bigint;
begin
  insert into mock_portfolios (user_id, name, source, value_mode)
  values (auth.uid(), p_name, p_source, p_value_mode)
  returning id into v_id;

  insert into mock_portfolio_items (mock_portfolio_id, user_id, asset_class, label, value)
  select v_id, auth.uid(), x.asset_class, x.label, x.value
  from jsonb_to_recordset(p_items) as x(asset_class text, label text, value numeric);

  return v_id;
end;
$$;

grant execute on function create_mock_portfolio_bulk(text, text, text, jsonb) to authenticated;
